exec-once = uwsm-app $(python /home/shady/.config/Shady-XShell/main.py)
exec = pgrep -x "hypridle" > /dev/null || uwsm app -- hypridle
exec = uwsm app -- awww-daemon
exec-once =  wl-paste --type text --watch cliphist store
exec-once =  wl-paste --type image --watch cliphist store

$fabricSend = fabric-cli exec shady-xshell

# Wallpapers directory: /home/shady/Wallpaper

source = /home/shady/.config/Shady-XShell/config/hypr/colors.conf

layerrule {
    name = fabric_no_anim
    no_anim = on
    match:namespace = fabric
}

exec = exec = ln -sf "$wallpaper" ~/.current.wall

general {
    col.active_border = rgb($primary)
    col.inactive_border = rgb($surface)
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    layout = dwindle
}


decoration {
    blur {
        enabled = yes
        size = 1
        passes = 3
        new_optimizations = yes
        contrast = 1
        brightness = 1
    }
    rounding = 14
    shadow {
      enabled = true
      range = 10
      render_power = 2
      color = rgba(0, 0, 0, 0.25)
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.4, 0.0, 0.2, 1.0
    animation = windows, 1, 2.5, myBezier, popin 80%
    animation = border, 1, 2.5, myBezier
    animation = fade, 1, 2.5, myBezier
    animation = workspaces, 1, 2.5, myBezier, slidefade 20%
}
